### PR TITLE
Remove legacy ripemd160 hash

### PR DESCRIPTION
**Pull request by fepitre**
Remove also Travis CI file.

### CODE REVIEW

**Comment by marmarek** [comment]
I've merged the first commit. As for others, I'll keep it open until pyproject.toml support will be more broadly available.

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry+head

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Pull request merged**
